name: Build Prebuilds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxtst-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libxss-dev \
          libxfixes-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxcb1-dev \
          libxcb-render0-dev \
          libxcb-render-util0-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxcb-xinerama0-dev \
          libxcb-xkb-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          build-essential \
          python3
    
    - name: Install dependencies
      run: npm install
      env:
        npm_config_build_from_source: true
    
    - name: Build prebuilds
      run: npm run prebuildify
      shell: bash
      env:
        npm_config_build_from_source: true
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prebuilds-${{ matrix.os }}
        path: prebuilds/
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: prebuilds/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 